version: '3.8'

services:
  song-service-db:
    image: postgres:latest
    container_name: song-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: song_service_db
    ports:
      - "5432:5432"
    volumes:
      - song-service-db-data:/var/lib/postgresql/data

  resource-service-db:
    image: postgres:latest
    container_name: resoucre-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource_service_db
    ports:
      - "5433:5432"
    volumes:
      - resource-service-db-data:/var/lib/postgresql/data

  resoucre-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    container_name: resource-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://resoucre-service-db:5432/resource_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - resource-service-db

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    container_name: song-service
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://song-service-db:5432/song_service_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        RESOURCE_SERVICE_URL: http://resoucre-service:8080
    depends_on:
        - song-service-db

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - resource-service-db

volumes:
    song-service-db-data:
        driver: local
    resource-service-db-data:
        driver: local