server:
  port: 8081

spring:
  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5432/song_service_db}
    username: ${SONG_DB_USERNAME:postgres}
    password: ${SONG_DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true