server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: song-service
  datasource:
    url: ${SONG_DB_URL:jdbc:postgresql://localhost:5432/song_service_db}
    username: ${SONG_DB_USERNAME:postgres}
    password: ${SONG_DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true