server:
  port: 8080

spring:
  application:
    name: resource-service
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5433/resource_service_db}
    username: ${RESOURCE_DB_USERNAME:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  cloud:
    aws:
      credentials:
        access-key: STUB
        secret-key: STUB
      endpoint: http://localhost:4566

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

song-service:
  name: song-service
  url: ${SONG_SERVICE_URL:http://localhost:8081}



aws:
  region: ${AWS_REGION:us-west-2}
s3:
  resource-bucket: ${RESOURCE_BUCKET:resource-bucket}



