server:
  port: 8080

spring:
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5433/resource_service_db}
    username: ${RESOURCE_DB_USERNAME:postgres}
    password: ${RESOURCE_DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

song-service:
  name: song-service
  url: ${SONG_SERVICE_URL:http://localhost:8081}